
# CI that runs when a tag is pushed to any branch other than main, and creates a PR to merge the tag into main

name: CI
on:
  push:
    branches-ignore:
      - main
  tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Merge tag ${{ github.ref }} into main
        title: Merge tag ${{ github.ref }} into main
        body: |
          Merge tag ${{ github.ref }} into main
        branch: main
        delete-branch: true
        # Set tag author as PR assignee
        assignees: ${{ github.event.pusher.name }}
        commit-option: squash

